# -*- coding: utf-8 -*-
"""survey lung Using DecisionTreeClassifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MAqtU8Cn-v1-MjQdos6e6cM2qwknHhbE
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
df=pd.read_csv('/content/survey lung cancer.csv')
df.head(10)

df.tail(13)

df.shape

df.info()

df.describe()

a=df['CHEST PAIN']
plt.plot(a)

b=df['LUNG_CANCER']
c=df['CHRONIC DISEASE']
plt.scatter(b,c)

d=df['COUGHING']
plt.bar(d,width=100,height=100)

e=df['ALLERGY ']
plt.hist(e)

f=df['CHEST PAIN']
plt.pie(f)

a1=df['CHRONIC DISEASE']
a2=df['ANXIETY']
sns.lineplot(x=a1,y=a2,data=df)

b1=df['GENDER']
b2=df['ANXIETY']
sns.scatterplot(x=b1,y=b2,data=df)

c1=df['SHORTNESS OF BREATH']
c2=df['CHRONIC DISEASE']
sns.barplot(x=c1,y=c2,data=df)

sns.countplot(x='CHRONIC DISEASE',data=df)

sns.pairplot(df,hue='CHRONIC DISEASE')

A=[12,5,6,65,36,543]
B=[10,20,30,40,50,60]
sns.distplot(A,B)

df.isnull().sum()

a=df['AGE']
sns.boxplot(a)

x

from sklearn.preprocessing import LabelEncoder

a=LabelEncoder()

g=df['GENDER']
g

df['GENDER']=a.fit_transform(g)

v=df['LUNG_CANCER']
v

df['LUNG_CANCER']=a.fit_transform(y)

x=df.drop('LUNG_CANCER',axis=1)

y=df['LUNG_CANCER']
y

from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

x_train.shape

x_test.shape

from sklearn.preprocessing import StandardScaler

a=StandardScaler()

x_train

X=a.fit_transform(x_train)

X

from sklearn.tree import DecisionTreeClassifier

a=DecisionTreeClassifier()

a.fit(x_train,y_train)

pred=a.predict(x_test)

from sklearn.metrics import accuracy_score

accuracy_score(pred,y_test)

from sklearn.metrics import confusion_matrix

confusion_matrix(pred,y_test)